### PR TITLE
Amora themer

### PR DESCRIPTION
**Pull request by CRAG666**
theme inspired in amora
https://github.com/owozsh/amora

### CODE REVIEW

**Review by bryant-the-coder — COMMENTED** [review]
tbh u dun need add anything to the readme as for now

**Comment by CRAG666** [comment]
> tbh u dun need add anything to the readme as for now

my mistake, I thought it was necessary right now I remove this

**Comment by CRAG666** [comment]
@bryant-the-coder ready change echo

**Comment by bryant-the-coder** [comment]
@CRAG666 astro is currenly resting after making this plugin. my pr is also being held. please kindly be patient for the next task. over

**Pull request merged**
